include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_single_quotes
    - sort_child_properties_last

analyzer:
  errors:
    todo: info
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart" 