name: Deploy Flutter Web to Cloudflare Pages

on:
  push:
    branches:
      - AI 
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: Deploy to Cloudflare Pages
        run: |
          npm install -g wrangler
          wrangler pages deploy ./build/web \
            --project-name ${{ secrets.CLOUDFLARE_PROJECT_NAME }} \
            --account-id ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} \
            --api-token ${{ secrets.CLOUDFLARE_API_TOKEN }}
